/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Course, Department, CourseComment, UserProfile } from "./types";

// Supported departments for Major and Minor
export const DEPARTMENTS: Department[] = [
  {
    id: "010",
    name: "新聞學系",
    code: "010",
    totalRequiredCredits: 20,
    requiredCoreCredits: 0,
    electiveCredits: 20,
    intro: "新聞學系輔系生畢業前需自規定選課表中修畢至少 20 學分。表列科目皆為 2 學分專業核心課程，由學生依興趣自由規劃修習，全學年課程（如新聞英文）需修滿上下學期方可列計學分。"
  },
  {
    id: "040",
    name: "圖文傳播暨數位出版學系",
    code: "040",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "整合攝影、平面設計、包裝、數位出版、排版印刷技術與專案管理之視覺傳播學術精隨。"
  },
  {
    id: "050",
    name: "公共關係暨廣告學系",
    code: "050",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "傳授公關品牌危機處理、社會溝通、廣告行銷企劃與整合行銷傳播（IMC）之核心創意產業能力。"
  },
  {
    id: "060",
    name: "口語傳播暨社群媒體學系",
    code: "060",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "鑽研口語表達、人際溝通、演說談判及社群媒體行銷策略，打造跨載體意見領袖培育基地。"
  },
  {
    id: "070",
    name: "資訊傳播學系",
    code: "070",
    totalRequiredCredits: 29,
    requiredCoreCredits: 17,
    electiveCredits: 12,
    intro: "融合資訊科技、數位內容與傳播美學，培育行動應用開發、互動網頁與電路數位控制跨域菁英。"
  },
  {
    id: "080",
    name: "數位多媒體設計學系",
    code: "080",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "培養多媒體素材整合、互動科技應用與動態藝術發想，打造新世代多元數位創意設計人才。"
  },
  {
    id: "210",
    name: "傳播管理學系",
    code: "210",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "融合傳播媒介特質與商業管理學，探討媒體經營、娛樂行銷、版權營運與大數據媒體受眾分析。"
  },
  {
    id: "221",
    name: "資訊管理學系資訊管理組",
    code: "221",
    totalRequiredCredits: 20,
    requiredCoreCredits: 9,
    electiveCredits: 11,
    intro: "培養卓越程式設計、網頁前後端整合與軟體專案架構邏輯，是進入軟體轉碼工程領域的不二選擇。"
  },
  {
    id: "222",
    name: "資訊管理學系人工智慧暨科技傳播組",
    code: "222",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "研習機器學習、雲端科技與傳播產業AI落地，將先進科技成果融入互動式新媒體傳播中。"
  },
  {
    id: "230",
    name: "財務金融學系",
    code: "230",
    totalRequiredCredits: 29,
    requiredCoreCredits: 24,
    electiveCredits: 5,
    intro: "分析資本市場與金流操作。輔系學生在基礎指定必修 24 學分（含會計、統計、貨銀、財管與投資學等核心）外，需另選修 5 學分專業課程以培養跨領域金融分析思維。"
  },
  {
    id: "240",
    name: "行政管理學系",
    code: "240",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "探討公部門決策、政策分析、非營利組織管理與多元人力資源策劃，為公共治理奠定堅實底蘊。"
  },
  {
    id: "260",
    name: "經濟學系",
    code: "260",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "講述個體與總體經濟學核心原理、博弈論與數據計量分析，是洞察現代多變市場機遇的重要基石。"
  },
  {
    id: "270",
    name: "企業管理學系",
    code: "270",
    totalRequiredCredits: 18,
    requiredCoreCredits: 6,
    electiveCredits: 12,
    intro: "奠定商業邏輯、組織架構與市場思維。輔系提供管理學、行銷、組織行為、專案規劃等，適合各領域跨界整合。"
  },
  {
    id: "310",
    name: "社會心理學系",
    code: "310",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "融合社會學與心理學視角，引導學生研討團體心理、消費者偏好行徑、人際動態與心理諮商基礎。"
  },
  {
    id: "320",
    name: "英語暨傳播應用學系",
    code: "320",
    totalRequiredCredits: 16,
    requiredCoreCredits: 6,
    electiveCredits: 10,
    intro: "著重英美文學、數位跨國傳播及英語實務應對。輔系旨在深化全球化溝通、外文寫作與翻譯素事理念。"
  },
  {
    id: "330",
    name: "中國文學系",
    code: "330",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "傳承華夏經典文學、古今散文與創意劇本寫作之粹，培養數位內容寫作與文案策劃之筆鋒大師。"
  },
  {
    id: "340",
    name: "日本語文學系",
    code: "340",
    totalRequiredCredits: 26,
    requiredCoreCredits: 18,
    electiveCredits: 8,
    intro: "日本語文學系輔系畢業學分共 26 學分，包含 18 學分指定必修課程（初、中級日語及初級日語會話），以及至少 8 學分的日文系選修課程。"
  },
  {
    id: "400",
    name: "法律學系",
    code: "400",
    totalRequiredCredits: 20,
    requiredCoreCredits: 8,
    electiveCredits: 12,
    intro: "講授民商法、刑法、智慧財產權與傳播法規。培育兼具傳播智識之跨界卓越法務法學先鋒。"
  }
];

// Dynamically parsed from user database to Course standard schema
export const COURSES: Course[] = [
  // ==========================================
  // 1. INFO (資訊傳播學系 - 070)
  // ==========================================
  {
    id: "info_101_01_a1",
    code: "INFO-101-01-A1",
    name: "資訊傳播概論 Intro to Information & Communication",
    departmentId: "070",
    credits: 2,
    instructor: "莊道明",
    timeSlots: [{ day: 1, slots: [1, 2] }],
    location: "G502",
    syllabus: "大一必修。介紹資訊傳播理論、數位科技、數位內容與人機互動等基礎知能，為資傳系之物理與人文底蘊學術。輔系指定必修學科。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_115_01_a1",
    code: "INFO-115-01-A1",
    name: "資訊行銷 Information Marketing",
    departmentId: "070",
    credits: 2,
    instructor: "陳貞妃",
    timeSlots: [{ day: 2, slots: [3, 4] }],
    location: "R602",
    syllabus: "大一必修。講授行銷學基礎原理，並聚焦於數位資訊商品、新媒體平台與線上受眾分析的行銷策略。輔系指定必修學科。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_210_01_a1",
    code: "INFO-210-01-A1",
    name: "數位內容設計 Digital Content Design",
    departmentId: "070",
    credits: 2,
    instructor: "連英佑",
    timeSlots: [{ day: 3, slots: [6, 7] }],
    location: "L502",
    syllabus: "大二必修。探討數位媒體多媒體素材設計、視覺傳達與使用者介面(UI)規劃，培養學生數位設計實作能力。輔系指定必修學科。",
    isRequired: true,
    category: "核心必修",
    isNotOfferedThisSemester: true
  },
  {
    id: "info_312_01_a1",
    code: "INFO-312-01-A1",
    name: "資料庫系統 Database Systems",
    departmentId: "070",
    credits: 2,
    instructor: "余顯強",
    timeSlots: [{ day: 4, slots: [3, 4] }],
    location: "M306",
    syllabus: "大三必修。教授資料庫正規化設計、關聯模型(Relational Model)以及結構化查詢語言(SQL)實作與管理。輔系指定必修學科。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_318_01_a1",
    code: "INFO-318-01-A1",
    name: "資訊資源組織 Information Resource Organization",
    departmentId: "070",
    credits: 2,
    instructor: "阮明淑",
    timeSlots: [{ day: 5, slots: [1, 2] }],
    location: "R901",
    syllabus: "大三必修。講授資訊分類、數位編目、Metadata與本體論，探討數位資訊資源的有效管理、檢索與組織架構。輔系指定必修學科。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_112_01_a1",
    code: "INFO-112-01-A1",
    name: "網路直播經營 Webcast Management",
    departmentId: "070",
    credits: 2,
    instructor: "莊道明",
    timeSlots: [{ day: 3, slots: [3, 4] }],
    location: "G502",
    syllabus: "網路直播不僅在個人行銷上具有很大的優勢，同時也可運用在品牌行銷上。本課程主要介紹網路直播的規劃與經營，主題包括網路直播的內容種類、設計、製作與拍攝、上線放映工作事項、觀眾經營以及內容再利用等等。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "info_107_02_a1",
    code: "INFO-107-02-A1",
    name: "網頁設計 Web-page Design",
    departmentId: "070",
    credits: 3,
    instructor: "林頌堅",
    timeSlots: [{ day: 2, slots: [6, 7, 8] }],
    location: "M308",
    syllabus: "全世界網際網路Web伺服器的數量每十星期數量就會成長一倍。Web已成為政府、組織、公司、團體或個人重要的行銷管道。然而一個好的網站必須同時具備內容及資訊技術的兩個構面的呈現。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_117_01_a1",
    code: "INFO-117-01-A1",
    name: "數位內容策展 Digital Content Curation",
    departmentId: "070",
    credits: 2,
    instructor: "黃昭謀",
    timeSlots: [{ day: 4, slots: [3, 4] }],
    location: "R901",
    syllabus: "隨著ICT發展與社群媒體之盛行，改變了資訊傳播方式，因而產生網路資訊整合服務的需求。傳授數位內容策展之類型、來源管道及實例分析，培養同學數位內容策展之辨識、選擇、組織與呈現能力。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_107_01_a1",
    code: "INFO-107-01-A1",
    name: "網頁設計 Web-page Design",
    departmentId: "070",
    credits: 3,
    instructor: "連英佑",
    timeSlots: [{ day: 4, slots: [6, 7, 8] }],
    location: "L502",
    syllabus: "全世界網際網路Web伺服器的數量每十星期數量就會成長一倍。Web已成為政府、組織、公司、團體或個人重要的行銷管道。第一階段教導主題包含網頁內容規劃分析，第二階段包含版面製作與美工設計等。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_117_02_a1",
    code: "INFO-117-02-A1",
    name: "數位內容策展 Digital Content Curation",
    departmentId: "070",
    credits: 2,
    instructor: "阮明淑",
    timeSlots: [{ day: 2, slots: [6, 7] }],
    location: "R901",
    syllabus: "隨著ICT發展與社群媒體之盛行，改變了資訊傳播方式，因而產生網路資訊整合服務的需求。本課程介紹數位內容策展之類型、來源管道及實例分析。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_205_01_a1",
    code: "INFO-205-01-A1",
    name: "互動程式設計 Designing of Interactive Procedure",
    departmentId: "070",
    credits: 2,
    instructor: "余顯強",
    timeSlots: [{ day: 5, slots: [3, 4] }],
    location: "L406",
    syllabus: "此為延續性課程，學習以Java Service Pages(JSP)程式開發動態網頁的應用程式。並透過學習過程了解前端瀏覽器、Web伺服器與後端資料三者之間的關係與運作方式。二年級分班（學號尾數1、2、3修本班）。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_205_02_a1",
    code: "INFO-205-02-A1",
    name: "互動程式設計 Designing of Interactive Procedure",
    departmentId: "070",
    credits: 2,
    instructor: "劉立民",
    timeSlots: [{ day: 5, slots: [3, 4] }],
    location: "W401",
    syllabus: "此為延續性課程，學習以Java Service Pages(JSP)程式開發動態網頁的應用程式。並透過學習過程了解前端瀏覽器、Web伺服器與後端資料關係。二年級分班（學號尾數4、5、6修本班）。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_205_03_a1",
    code: "INFO-205-03-A1",
    name: "互動程式設計 Designing of Interactive Procedure",
    departmentId: "070",
    credits: 2,
    instructor: "陳俊廷",
    timeSlots: [{ day: 5, slots: [8, 9] }],
    location: "L406",
    syllabus: "此為延續性課程，學習以Java Service Pages(JSP)程式開發動態網頁的應用程式。並透過學習過程了解架構。二年級分班（學號尾數7、8、9、0修本班）。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_212_01_a1",
    code: "INFO-212-01-A1",
    name: "資訊心理學 Information Psychology",
    departmentId: "070",
    credits: 2,
    instructor: "陳貞妃",
    timeSlots: [{ day: 4, slots: [8, 9] }],
    location: "R602",
    syllabus: "藉由對人類心智系統的探究，從行為的生理基礎、感覺與知覺、認知與學習歷程來了解資訊對人的影響，並增加對資訊使用者的瞭解，進而控掘人機互動關係。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "info_236_01_a1",
    code: "INFO-236-01-A1",
    name: "網站規劃與設計 Planning and Designing of Web Sites",
    departmentId: "070",
    credits: 3,
    instructor: "林頌堅",
    timeSlots: [{ day: 4, slots: [2, 3, 4] }],
    location: "R502",
    syllabus: "本課程第一階段著重於內容規劃，包括網站規劃的需求分析與資料蒐集，定義網頁關鍵需求；第二階段以軟體設計為主，包括設計平台、版面美工與互動效果等。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "info_237_01_a1",
    code: "INFO-237-01-A1",
    name: "系統分析 System Analysis",
    departmentId: "070",
    credits: 3,
    instructor: "余顯強",
    timeSlots: [{ day: 3, slots: [8, 9, 10] }],
    location: "G502",
    syllabus: "本課程介紹系統分析與設計的基本知識，如概念、技巧、方法、技術以及專案管理工具等，主要的目的是希望藉由完整的程序步驟，使學生瞭解開發資訊系統的觀念。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "info_240_01_a1",
    code: "INFO-240-01-A1",
    name: "人工智慧與傳播科技應用 Artificial Intelligence",
    departmentId: "070",
    credits: 3,
    instructor: "陳俊廷",
    timeSlots: [{ day: 2, slots: [3, 4, 5] }],
    location: "W401",
    syllabus: "介紹人工智慧的理論基礎與傳播領域相關應用案例，讓學生瞭解人工智慧的運作基礎、機器學習、內容生成以及當前假新聞辨識、媒體信任等實務應用。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "info_241_01_a1",
    code: "INFO-241-01-A1",
    name: "英語直播: 口語表達 Live English",
    departmentId: "070",
    credits: 2,
    instructor: "楊盛昱",
    timeSlots: [{ day: 2, slots: [8, 9] }],
    location: "C101",
    syllabus: "Live-streaming English: Oral Communication Skills. 全英文授課。藉由各種直播主題以提升同學英語口語表達能力，並訓練同學熟悉特殊實用的英語搭配詞。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "info_243_01_a1",
    code: "INFO-243-01-A1",
    name: "雲端平台與應用服務 Cloud Platforms",
    departmentId: "070",
    credits: 2,
    instructor: "劉立民",
    timeSlots: [{ day: 5, slots: [6, 7] }],
    location: "W401",
    syllabus: "完整介紹什麼是雲端運算，以三大雲端供應商GCP, AWS, Azure來實作演練各項平台上的IaaS, PaaS, 與SaaS等服務。並著眼於低程式與無程式開發平台實作。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "info_228_01_a1",
    code: "INFO-228-01-A1",
    name: "質性資料分析 Qualitative Research",
    departmentId: "070",
    credits: 2,
    instructor: "黃昭謀",
    timeSlots: [{ day: 1, slots: [6, 7] }],
    location: "R501",
    syllabus: "本課程旨在介紹質化研究的理論基礎及實施步驟，目的在訓練學生習得質性研究的資料蒐集、分析及撰寫等技巧。包括深度訪談、參與觀察和焦點團體訪談。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_228_02_a1",
    code: "INFO-228-02-A1",
    name: "質性資料分析 Qualitative Research",
    departmentId: "070",
    credits: 2,
    instructor: "黃昭謀",
    timeSlots: [{ day: 3, slots: [3, 4] }],
    location: "J306",
    syllabus: "合開課。本課程旨在介紹質化研究的理論基礎及實施步驟，目的在訓練學生習得質性研究的資料蒐集、深度訪談、參與觀察技巧。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_238_01_a1",
    code: "INFO-238-01-A1",
    name: "資訊傳播專題（一） Practicum I",
    departmentId: "070",
    credits: 2,
    instructor: "莊道明",
    timeSlots: [{ day: 1, slots: [3, 4] }],
    location: "CB205",
    syllabus: "以資訊傳播四年課程內容為範圍，根據個人研究興趣主題，自選一個主題完成作品。本課程透過發現問題、蒐集與組織資訊，培養專案管理與系統實作能力。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_238_02_a1",
    code: "INFO-238-02-A1",
    name: "資訊傳播專題（一） Practicum I",
    departmentId: "070",
    credits: 2,
    instructor: "阮明淑",
    timeSlots: [{ day: 4, slots: [6, 7] }],
    location: "CB201",
    syllabus: "以資訊傳播四年課程內容為範圍，自選一個主題完成作品。本課程透過發現問題、蒐集資料、過濾與組織資訊，培訓學生獨立解決與專案管理能力。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_227_01_a1",
    code: "INFO-227-01-A1",
    name: "資訊圖表設計 Infographic Design",
    departmentId: "070",
    credits: 3,
    instructor: "林頌堅",
    timeSlots: [{ day: 3, slots: [2, 3, 4] }],
    location: "G302",
    syllabus: "本課程介紹數位媒體上的資訊視覺呈現原理與可能應用，並且特別強調於統計圖表、地圖與圖解等方法的使用，培養學生卓越的視覺化圖表產製能力。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "info_335_01_a1",
    code: "INFO-335-01-A1",
    name: "數位產品技術加值 Digital Value-Adding",
    departmentId: "070",
    credits: 3,
    instructor: "楊志宏",
    timeSlots: [{ day: 4, slots: [12, 13, 14] }],
    location: "R203",
    syllabus: "介紹數位內容市場特性，資訊商品特性與行銷手段；訓練學生創新企劃、多媒體整合、互動式新媒體製作與設計等專業技能，完成兼具美學與科技之加值產品。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "info_364_01_a1",
    code: "INFO-364-01-A1",
    name: "知識管理與商業智慧 Knowledge Management",
    departmentId: "070",
    credits: 3,
    instructor: "阮明淑",
    timeSlots: [{ day: 3, slots: [8, 9, 10] }],
    location: "R102",
    syllabus: "本課程除介紹知識管理與商業智慧之內容外，並以實務之角度透析知識管理各流程之本質以及流程之間之串連，提供實用的數位決策與數據指標分析。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "info_368_01_a1",
    code: "INFO-368-01-A1",
    name: "生成式AI與商模創新 Generative AI",
    departmentId: "070",
    credits: 3,
    instructor: "江信昱",
    timeSlots: [{ day: 5, slots: [2, 3, 4] }],
    location: "R601",
    syllabus: "生成式AI（AIGC）的快速發展為商業模式帶來前所未有的機會。本課程主旨探討生成式AI在商業世界中的運用，並介紹其如何促成科技與商業模式的創新。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "info_354_01_a1",
    code: "INFO-354-01-A1",
    name: "數據資料分析 Quantitative Data Analysis",
    departmentId: "070",
    credits: 2,
    instructor: "莊道明",
    timeSlots: [{ day: 2, slots: [3, 4] }],
    location: "S303",
    syllabus: "有效蒐集、整理與解釋數據資料是重要技能。本課程利用統計學原理與統計分析工具，培養學生具備統計思維，將複雜數據細分轉譯為決策資訊。資傳三甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_354_02_a1",
    code: "INFO-354-02-A1",
    name: "數據資料分析 Quantitative Data Analysis",
    departmentId: "070",
    credits: 2,
    instructor: "黃柏堯",
    timeSlots: [{ day: 1, slots: [3, 4] }],
    location: "W401",
    syllabus: "有效蒐集、整理、分析與解釋數據。學習將網頁訊息與研究數據轉化為決策統計資料，有效達成傳播學學術研究目的。資傳三乙必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_362_01_a1",
    code: "INFO-362-01-A1",
    name: "資料庫系統開發實務 Database Modeling",
    departmentId: "070",
    credits: 2,
    instructor: "余顯強",
    timeSlots: [{ day: 4, slots: [4, 5] }],
    location: "M306",
    syllabus: "1. 資料庫規格設計: 學習正規化、實體關係圖(ERD)等圖示方法。 2. 前端應用程式存取資料庫之系統開發: 實作SQL資料搜尋、維護等功能網頁程式。資傳三甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_362_02_a1",
    code: "INFO-362-02-A1",
    name: "資料庫系統開發實務 Database Modeling",
    departmentId: "070",
    credits: 2,
    instructor: "劉立民",
    timeSlots: [{ day: 4, slots: [1, 2] }],
    location: "M303",
    syllabus: "學習資料庫正規化設計、關聯模型。第二階段學習前端網頁存取與呼叫，完成對關聯資料庫搜尋、寫入之實作開發。資傳三乙必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_366_01_a1",
    code: "INFO-366-01-A1",
    name: "資訊傳播專題（三） Practicum III",
    departmentId: "070",
    credits: 2,
    instructor: "江信昱",
    timeSlots: [{ day: 1, slots: [6, 7] }],
    location: "R704",
    syllabus: "資傳三甲必修。以四年課程為範圍，自選興趣主題完成一份畢業作品（APP、網頁或電路控制裝置），展現實作、整合與專案簡報能力。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_366_02_a1",
    code: "INFO-366-02-A1",
    name: "資訊傳播專題（三） Practicum III",
    departmentId: "070",
    credits: 2,
    instructor: "郭冠麟",
    timeSlots: [{ day: 1, slots: [6, 7] }],
    location: "CB201",
    syllabus: "合開課。資傳三乙必修。整合四年技術內容，從硬體、前端、資料庫三大構面開發數位資訊專題作品，落實專案管控與簡報溝通。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "info_441_01_a1",
    code: "INFO-441-01-A1",
    name: "網路傳播與生成式AI Internet & AI",
    departmentId: "070",
    credits: 2,
    instructor: "黃昭謀",
    timeSlots: [{ day: 2, slots: [6, 7] }],
    location: "R203",
    syllabus: "網路傳播已成數位時代主要溝通方式，生成式AI之強大生成能力正深刻演變線上內容。本課程引導同學研究實用之傳播模型，並操作最新的AI內容生成，具備前沿思維。四年級必修。",
    isRequired: true,
    category: "核心必修"
  },

  // ==========================================
  // 2. PRAD (公共關係暨廣告學系 - 050)
  // ==========================================
  {
    id: "prad_109_01_a1",
    code: "PRAD-109-01-A1",
    name: "廣告創意 Advertising Creativity",
    departmentId: "050",
    credits: 2,
    instructor: "洪琬婷",
    timeSlots: [{ day: 1, slots: [3, 4] }],
    location: "J103",
    syllabus: "本課程旨在提供創造性思考和策略性思考方法，讓廣告系學生能有系統地形塑廣告創意理念。課程包含實用的廣告文案寫作基礎訓練，對應114輔系門檻標準學科。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "prad_109_02_a1",
    code: "PRAD-109-02-A1",
    name: "廣告創意 Advertising Creativity",
    departmentId: "050",
    credits: 2,
    instructor: "蕭湘文",
    timeSlots: [{ day: 3, slots: [1, 2] }],
    location: "R602",
    syllabus: "引導學生在日常生活中訓練策略性思維與新奇獨創，符合廣告活動中的攸關性、解決銷售與行銷傳播挑戰，落實文案之情感召喚與寫作基礎訓練。輔系可修。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "prad_124_01_a1",
    code: "PRAD-124-01-A1",
    name: "媒體關係 Media Relations",
    departmentId: "050",
    credits: 2,
    instructor: "應淇帆",
    timeSlots: [{ day: 4, slots: [1, 2] }],
    location: "R102",
    syllabus: "說明新聞媒體結構、特質與公共關係之運作。探討公關人員與新聞記者之互動，熟悉媒體分支作業流程、新聞價值判斷，維持雙贏媒體關係。輔系核定科目。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "prad_124_02_a1",
    code: "PRAD-124-02-A1",
    name: "媒體關係 Media Relations",
    departmentId: "050",
    credits: 2,
    instructor: "吳耀仁",
    timeSlots: [{ day: 2, slots: [3, 4] }],
    location: "CB308",
    syllabus: "公關實務的核心拼圖。研究媒體關係建構、新聞稿發布時機、公共議題包裝與置入時機。輔系認證科目。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "prad_102_01_a1",
    code: "PRAD-102-01-A1",
    name: "行銷學 Marketing",
    departmentId: "050",
    credits: 2,
    instructor: "蕭湘文",
    timeSlots: [{ day: 2, slots: [8, 9] }],
    location: "R403",
    syllabus: "提供完整的行銷組合(4P)、市場區隔與定位(STP)、數位行銷和行銷策略。訓練撰寫整合行銷企劃書，為輔系指定必修課程。公廣一甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_102_02_a1",
    code: "PRAD-102-02-A1",
    name: "行銷學 Marketing",
    departmentId: "050",
    credits: 2,
    instructor: "許安琪",
    timeSlots: [{ day: 1, slots: [6, 7] }],
    location: "CB203",
    syllabus: "行銷基礎知識。講授商戰管理、數位轉換與市場受眾分析。公廣一乙必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_280_01_a1",
    code: "PRAD-280-01-A1",
    name: "社群媒體行銷 Social Media Marketing",
    departmentId: "050",
    credits: 2,
    instructor: "鄭佳興",
    timeSlots: [{ day: 5, slots: [6, 7] }],
    location: "R301",
    syllabus: "了解各社群平台之差異與分眾黏著，發展行銷內容，依數據分析改善黏著。對接最新輔系學程名單。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "prad_286_01_a1",
    code: "PRAD-286-01-A1",
    name: "數位AI融合圖像廣告創作 Digital AI Drawing",
    departmentId: "050",
    credits: 2,
    instructor: "杜雅雯",
    timeSlots: [{ day: 1, slots: [8, 9] }],
    location: "L406",
    syllabus: "教授學生掌握與善用AI圖像科技來增加廣告創作之多元性，簡化工作流程，並使用專業美工與提示詞技巧，產出具備高渲染力之廣告海報。輔系核定選修學科。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "prad_220_01_a1",
    code: "PRAD-220-01-A1",
    name: "消費行為 Consumer Behavior",
    departmentId: "050",
    credits: 2,
    instructor: "蕭湘文",
    timeSlots: [{ day: 1, slots: [1, 2] }],
    location: "R501",
    syllabus: "從事廣告、公關與行銷的核心知能。理解消費者內在心理、動機、感知、決策模式。公關策略與廣告策略必修二選一。公廣二甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_278_01_a1",
    code: "PRAD-278-01-A1",
    name: "廣告策略與企劃 Advertising Strategies",
    departmentId: "050",
    credits: 2,
    instructor: "杜雅雯",
    timeSlots: [{ day: 1, slots: [3, 4] }],
    location: "R503",
    syllabus: "廣告必修二選一核心課程。教導學生如何作廣告活動策略規劃，包含人性洞察、痛點提取與創意簡報(Creative Brief)撰寫。公廣二甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_279_01_a1",
    code: "PRAD-279-01-A1",
    name: "危機與議題管理 Crisis & Issue Management",
    departmentId: "050",
    credits: 2,
    instructor: "陳一香",
    timeSlots: [{ day: 4, slots: [8, 9] }],
    location: "CB301",
    syllabus: "公關領域看板課程。研究議題偵測與防範、危機爆發之公關應變、道歉與輿情管理策略、危機記者會防禦演練。公廣二甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_220_02_a1",
    code: "PRAD-220-02-A1",
    name: "消費行為 Consumer Behavior",
    departmentId: "050",
    credits: 2,
    instructor: "徐暄淯",
    timeSlots: [{ day: 4, slots: [1, 2] }],
    location: "R402",
    syllabus: "理解影響消費者行為之各項社會、心理、情境因素。加強生活洞察與行銷洞察演練。公廣二乙必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_278_02_a1",
    code: "PRAD-278-02-A1",
    name: "廣告策略與企劃 Advertising Strategies",
    departmentId: "050",
    credits: 2,
    instructor: "湯宗翰",
    timeSlots: [{ day: 3, slots: [8, 9] }],
    location: "J101",
    syllabus: "學習洞察與數據研判。探討人性動態，並用一針見血的面貌撰寫廣告創意切入點。公廣二乙必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_279_02_a1",
    code: "PRAD-279-02-A1",
    name: "危機與議題管理 Crisis & Issue Management",
    departmentId: "050",
    credits: 2,
    instructor: "葉幼梅",
    timeSlots: [{ day: 1, slots: [1, 2] }],
    location: "R503",
    syllabus: "介紹公共關係在危機與議題管理之角色，學習企業、非營利組織解決輿論威脅的核心技巧。公廣二乙必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_304_01_a1",
    code: "PRAD-304-01-A1",
    name: "公關策略與企劃 PR Strategies and Plans",
    departmentId: "050",
    credits: 2,
    instructor: "張艾喆",
    timeSlots: [{ day: 3, slots: [3, 4] }],
    location: "M411",
    syllabus: "本課程旨在熟悉公關策略規劃之四步驟：問題界定、策略發展、執行與評估。此課程須參加校園公關提案競賽。必修二選一。公廣三甲必修。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "prad_373_01_a1",
    code: "PRAD-373-01-A1",
    name: "進階公共關係 Advanced Public Relations",
    departmentId: "050",
    credits: 2,
    instructor: "應淇帆",
    timeSlots: [{ day: 1, slots: [1, 2] }],
    location: "R601",
    syllabus: "探討公關新興趨勢！講授公關專業倫理、大數據與AI在公關的智慧應用、永續溝通(SDGs / ESG)以及敘事說服理論。公廣三甲必修。",
    isRequired: true,
    category: "核心必修"
  },

  // ==========================================
  // 3. FIN (財務金融學系 - 230)
  // ==========================================
  {
    id: "fin_acc1_01_a1",
    code: "FIN-105-01-A1",
    name: "會計學(一)(含實作演練 2H) Accounting I",
    departmentId: "230",
    credits: 3,
    instructor: "粘敏如",
    timeSlots: [{ day: 1, slots: [1, 2, 3] }],
    location: "M303",
    syllabus: "指定必修（24學分中之一）。講授會計基礎理論與實作演練，包括分錄、過帳、試算、調整及結帳等會計循環，以及編製損益表及資產負債表。輔系奠基。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "fin_acc2_01_a1",
    code: "FIN-106-01-A1",
    name: "會計學(二)(含實作演練 2H) Accounting II",
    departmentId: "230",
    credits: 3,
    instructor: "粘敏如",
    timeSlots: [{ day: 2, slots: [1, 2, 3] }],
    location: "M303",
    syllabus: "指定必修（24學分中之一）。延續會計學(一)，研討公司債、股票發行、現金流量表及長期資產評價，掌握中級企業會計實務之帳務處理心法與流程。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["FIN-105-01-A1"]
  },
  {
    id: "fin_stat1_01_a1",
    code: "FIN-107-01-A1",
    name: "統計學(一)(含實作演練 1H) Statistics I",
    departmentId: "230",
    credits: 3,
    instructor: "蔡建源",
    timeSlots: [{ day: 3, slots: [2, 3, 4] }],
    location: "M411",
    syllabus: "指定必修（24學分中之一）。包括敘述統計學與推論統計學基礎，學習機率分配、抽樣分配、區間估計與假設檢定。培育全方位商業與財務決策量化分析之核心知能。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "fin_stat2_01_a1",
    code: "FIN-108-01-A1",
    name: "統計學(二)(含實作演練 1H) Statistics II",
    departmentId: "230",
    credits: 3,
    instructor: "蔡建源",
    timeSlots: [{ day: 4, slots: [2, 3, 4] }],
    location: "M411",
    syllabus: "指定必修（24學分中之一）。涵蓋變異數分析、簡單與多元線性迴歸分析、卡方檢定及無母數統計，探討財務金融大數據實證研究及推估模型實作。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["FIN-107-01-A1"]
  },
  {
    id: "fin_mby_01_a1",
    code: "FIN-201-01-A1",
    name: "貨幣銀行學 Money and Banking",
    departmentId: "230",
    credits: 3,
    instructor: "郭迺鋒",
    timeSlots: [{ day: 5, slots: [2, 3, 4] }],
    location: "M410",
    syllabus: "指定必修（24學分中之一）。探討貨幣制度、金融市場、銀行與金融機構管理，並研究央行貨幣政策、利率與匯率決定、通貨膨脹，奠定總體金融環境分析思維。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "fin_mgt1_01_a1",
    code: "FIN-215-01-A1",
    name: "財務管理(一) Financial Management I",
    departmentId: "230",
    credits: 3,
    instructor: "曾昭玲",
    timeSlots: [{ day: 2, slots: [6, 7, 8] }],
    location: "M412",
    syllabus: "指定必修（24學分中之一）。核心財務決策理論，研討貨幣時間價值（TVM）、證券與債券估值、資本預算決策與現金流量拆解。打下企業理財扎實基礎。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "fin_mgt2_01_a1",
    code: "FIN-216-01-A1",
    name: "財務管理(二) Financial Management II",
    departmentId: "230",
    credits: 3,
    instructor: "曾昭玲",
    timeSlots: [{ day: 3, slots: [6, 7, 8] }],
    location: "M412",
    syllabus: "指定必修（24學分中之一）。探討論公司資本結構、資金成本（WACC）、股利政策、營運資金管理，以及併購、企業融資實務，透析公司財務操作大局觀。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["FIN-215-01-A1"]
  },
  {
    id: "fin_204_01_a1",
    code: "FIN-204-01-A1",
    name: "投資學 Investments",
    departmentId: "230",
    credits: 3,
    instructor: "吳秋慧",
    timeSlots: [{ day: 1, slots: [6, 7, 8] }],
    location: "M411",
    syllabus: "指定必修（24學分中之一）。財務金融核心課程。探討風險與報酬權衡、證券評價、投資組合管理、資產定價模型(CAPM)等重要金融理論。實用且關鍵。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["FIN-215-01-A1"]
  },
  {
    id: "fin_112_01_a1",
    code: "FIN-112-01-A1",
    name: "財務科技與生活應用 FinTech Applications",
    departmentId: "230",
    credits: 3,
    instructor: "徐苑玲",
    timeSlots: [{ day: 4, slots: [6, 7, 8] }],
    location: "M308",
    syllabus: "選修課程。訓練同學能以最基本的試算表來處理財務計算及財務規劃。學習Excel內建財務函數、四則運算、格式等，厚植商業運算基本底子。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "fin_222_01_a1",
    code: "FIN-222-01-A1",
    name: "物聯網金融科技與DeFi概論 DeFi",
    departmentId: "230",
    credits: 3,
    instructor: "曾昭玲",
    timeSlots: [{ day: 5, slots: [6, 7, 8] }],
    location: "M405",
    syllabus: "選修課程。介紹物聯網之行動科技與去中心化金融(Decentralized Finance)，並探討區塊鏈、智慧合約所帶來的金融平台新型態，提升數位金融即戰力。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "fin_fsa_01_a1",
    code: "FIN-311-01-A1",
    name: "財務報表分析 Financial Statement Analysis",
    departmentId: "230",
    credits: 2,
    instructor: "粘敏如",
    timeSlots: [{ day: 2, slots: [4, 5] }],
    location: "M308",
    syllabus: "選修課程。研討如何解讀並分析利潤表、資產負債表及現金流量表之財務比率，評估企業財務結構、償債能力、經營效能及獲利狀況，實用性極高。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "fin_reg_01_a1",
    code: "FIN-322-01-A1",
    name: "證券投資信託與顧問法規 Securities Regulations",
    departmentId: "230",
    credits: 2,
    instructor: "許苑杰",
    timeSlots: [{ day: 4, slots: [1, 2] }],
    location: "M410",
    syllabus: "選修課程。研讀證券交易法、證券投資信託及顧問法、同業公會自律公約等核心法令。專為未來考取財金專業證照與投顧從業人員設計之必修實務課程。",
    isRequired: false,
    category: "基礎工具"
  },

  // ==========================================
  // 4. INF (資訊管理學系 - 221 / 222)
  // ==========================================
  {
    id: "inf_262_01_a1",
    code: "INF-262-01-a1",
    name: "生成式AI原理與實務 Generative AI",
    departmentId: "222",
    credits: 3,
    instructor: "胡碩誠",
    timeSlots: [{ day: 2, slots: [5, 6, 7] }],
    location: "M303",
    syllabus: "介紹生成式AI (AIGC) 背後的大型語言模型(LLM)、神經網路與擴散模型原理。實作包含提示詞工程、多模態媒體合成，對接產業數位化。科傳組必備選修。",
    isRequired: false,
    category: "進階應用"
  },
  // ==================== 資訊管理組 (221) 應修科目 ====================
  {
    id: "inf_248_01_a1",
    code: "INF-248-01-A1",
    name: "統計學(一) Statistics I",
    departmentId: "221",
    credits: 3,
    instructor: "蔡建源",
    timeSlots: [{ day: 4, slots: [6, 7, 8] }],
    location: "M406",
    syllabus: "院必修（資管組）。探討統計資料呈現、描述性統計測度、基本機率理論、機率分配（二項式、常態分配等）與單一或雙樣本之研究估計及抽樣分配等知能，精準理解學術研究及商業實踐之資料分佈面貌。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_106_01_a1",
    code: "INF-106-01-A1",
    name: "程式設計一 Programming I",
    departmentId: "221",
    credits: 3,
    instructor: "葉慶隆",
    timeSlots: [{ day: 1, slots: [2, 3, 4] }],
    location: "M303",
    syllabus: "系必修。著重於結構化設計概念之傳授、電腦系統之基本概念，配合流程圖分析及高階語言（Python / C++）程式分析與上機設計，內容包括基本輸入輸出、條件分支、多重迴圈操控、函數模組化拆析及系統調校。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_117_01_a1",
    code: "INF-117-01-A1",
    name: "程式設計二 Programming II",
    departmentId: "221",
    credits: 3,
    instructor: "李瑞庭",
    timeSlots: [{ day: 2, slots: [6, 7, 8] }],
    location: "M303",
    syllabus: "系必修。程式設計一之延續課程。著重物件導向程式設計（OOP）理念及語法，教授結構體、類別與物件定義、封裝、繼承與多型特性，搭配異常捕捉及檔案輸入輸出運作，打下全端前後端程式核心之底子。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_315_01_a1",
    code: "INF-315-01-A1",
    name: "資料庫系統 Database Systems",
    departmentId: "221",
    credits: 3,
    instructor: "劉清容",
    timeSlots: [{ day: 3, slots: [2, 3, 4] }],
    location: "M405",
    syllabus: "系必修。研析資料庫正規化（1NF至BCNF）、實體關係模型（ERD），以及結構化查詢語言（SQL）存取。第二階段實作關聯式資料庫系統建構、索引效能調優，適合未來要投身前後端網頁、大數據工程的人才修習。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_222_01_a1",
    code: "INF-222-01-A1",
    name: "資訊管理 Information Management",
    departmentId: "221",
    credits: 3,
    instructor: "鍾曉忠",
    timeSlots: [{ day: 1, slots: [6, 7, 8] }],
    location: "M308",
    syllabus: "資管組必修。從策略、組織與技術三大維度切入，討論企業資訊技術架構（ERP、CRM、SCM、BI）與數位轉型進程，並解密大數據、雲端計算與人工智慧在資訊安全防護及商管運作流程中之創新應用模式。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_245_01_a1",
    code: "INF-245-01-A1",
    name: "數據分析技法 Data Analysis Techniques",
    departmentId: "221",
    credits: 3,
    instructor: "蔡順慈",
    timeSlots: [{ day: 3, slots: [6, 7, 8] }],
    location: "M407",
    syllabus: "資管組必修。實習操作各種商業大數據探勘演算。內容包含關聯分析、決策樹分類（Decision Tree）、集群分析（Clustering）與深度預測分析模型。使用 R 與 Python 分析工具實機操作，厚植智慧商業決策力。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_249_01_a1",
    code: "INF-249-01-A1",
    name: "統計學(二) Statistics II",
    departmentId: "221",
    credits: 3,
    instructor: "蔡建源",
    timeSlots: [{ day: 5, slots: [2, 3, 4] }],
    location: "M406",
    syllabus: "資管組必修。統計學(一)進階。探討卡方分配、變異數分析、單一與多元線性迴歸模型、無母數統計檢定以及統計預估技術。培育企業決策及論文研究所需之高級推論與複數量化分析能力。",
    isRequired: true,
    category: "核心必修"
  },

  // ==================== 人工智慧暨科技傳播組 (222) 應修科目 ====================
  {
    id: "inf_112_01_a2",
    code: "INF-112-01-A2",
    name: "機率與統計 Probability & Statistics",
    departmentId: "222",
    credits: 3,
    instructor: "陳昭振",
    timeSlots: [{ day: 4, slots: [2, 3, 4] }],
    location: "M310",
    syllabus: "院必修（AI科傳組）。教授機率空間、條件機率、貝氏定理、離散/連續型隨機變數、期望值與變異數、大數法則及中央極限定理。此課程係機器學習、深度學習及資料科學工程領域中不可或缺的學術基石。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_106_01_a2",
    code: "INF-106-01-A2",
    name: "程式設計一 Programming I",
    departmentId: "222",
    credits: 3,
    instructor: "葉慶隆",
    timeSlots: [{ day: 1, slots: [2, 3, 4] }],
    location: "M303",
    syllabus: "系必修。著重於結構化設計概念之傳授、電腦系統之基本概念，配合流程圖分析及高階語言程式分析與上機設計，內容包括基本輸入輸出、條件分支、多重迴圈、函數與模組拆構，以資通工程視角奠定邏輯深度。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_117_01_a2",
    code: "INF-117-01-A2",
    name: "程式設計二 Programming II",
    departmentId: "222",
    credits: 3,
    instructor: "李瑞庭",
    timeSlots: [{ day: 2, slots: [6, 7, 8] }],
    location: "M303",
    syllabus: "系必修。教授物件導向程式設計（OOP）理念。涵蓋類別封裝、資源管理、繼承多型運作、抽象介面設計與檔案存取操作，使同學具備物件導向架構之獨立大型專案程式撰寫及物件拆解重組之全功能思維。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_315_01_a2",
    code: "INF-315-01-A2",
    name: "資料庫系統 Database Systems",
    departmentId: "222",
    credits: 3,
    instructor: "劉清容",
    timeSlots: [{ day: 3, slots: [2, 3, 4] }],
    location: "M405",
    syllabus: "系必修。講授關聯式資料庫引擎實體設計與管理、資料庫正規化（1NF~BCNF）、實體關係模型（ERD），學會進階 SQL 條件聯表查詢與維護，並銜接現代 API 前後端架構之資料串接與事務管理事務。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_132_01_a2",
    code: "INF-132-01-A2",
    name: "科技傳播導論 Introduction to Tech Communication",
    departmentId: "222",
    credits: 2,
    instructor: "許淑娟",
    timeSlots: [{ day: 2, slots: [3, 4] }],
    location: "M401",
    syllabus: "AI科傳組必修。研究網路世代之科技傳播形式、社群演算法分眾機制與數位媒體媒介演變。探索多螢跨媒體平台整合、沉浸式科技（AR/VR）等新興媒介在資訊內容分發與宣導之融合案例及應用。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_255_01_a2",
    code: "INF-255-01-A2",
    name: "人工智慧 Artificial Intelligence",
    departmentId: "222",
    credits: 3,
    instructor: "胡碩誠",
    timeSlots: [{ day: 5, slots: [6, 7, 8] }],
    location: "M403",
    syllabus: "AI科傳組必修。引入機器學習之監督式與非監督式學習模型、類神經網路、深度學習與電腦視覺、自然語言處理。針對當前生成式AI（AIGC）浪潮之產業落地，探討新媒體內容合成與假訊息辨識、演算法偏見等實務議題。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_257_01_a2",
    code: "INF-257-01-A2",
    name: "物件導向程式設計與 AI 協作 OOP & AI Collaboration",
    departmentId: "222",
    credits: 3,
    instructor: "胡碩誠",
    timeSlots: [{ day: 1, slots: [6, 7, 8] }],
    location: "M403",
    syllabus: "AI科傳組必修。結合深居核心的 OOP 觀念（多型、介面設計）與引領浪潮的「生成式 AI（如 GitHub Copilot、ChatGPT）協同程式撰寫法」。引導同學學習如何下精準 Prompt 進行代碼生成、防錯測試與優雅的重組，具備高效率敏捷開發思維。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_212_01_a2",
    code: "INF-212-01-A2",
    name: "資料結構 Data Structures",
    departmentId: "222",
    credits: 3,
    instructor: "葉慶隆",
    timeSlots: [{ day: 3, slots: [2, 3, 4] }],
    location: "M305",
    syllabus: "AI科傳組必修。深度探討記憶體底層與邏輯結構配置：線性串列（Linked List）、堆疊與雙向佇列（Stack/Queue）、二元樹與平衡樹、紅黑樹與哈希表。提升資料存取排序性能，為頂尖 AI 開發必修工具。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_258_01_a2",
    code: "INF-258-01-A2",
    name: "智慧網路技術與科技傳播 Smart Networks & Tech Communication",
    departmentId: "222",
    credits: 3,
    instructor: "曾聖元",
    timeSlots: [{ day: 5, slots: [2, 3, 4] }],
    location: "M306",
    syllabus: "AI科傳組必修。探討 TCP/IP 網路通訊協定、智慧物聯網感知（IoT）、邊緣計算，與數位多媒體影音之串流技術傳遞融合。剖析 5G 寬頻、雲端與智慧網路如何演變新一代直播及智慧傳播平台架構。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_319_01_a2",
    code: "INF-319-01-A2",
    name: "演算法 Algorithms",
    departmentId: "222",
    credits: 3,
    instructor: "葉慶隆",
    timeSlots: [{ day: 4, slots: [6, 7, 8] }],
    location: "M305",
    syllabus: "AI科傳組必修。精進程式思維核心。研習時間/空間複雜度分析（Big-O notation）、貪婪演算法、動態規劃（Dynamic Programming）、分治法與图論搜尋。培訓卓越計算思維與複雜系統演算實戰力。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "inf_382_01_a2",
    code: "INF-382-01-A2",
    name: "作業系統與 Linux 實務 OS & Linux Practicum",
    departmentId: "222",
    credits: 3,
    instructor: "鍾曉忠",
    timeSlots: [{ day: 2, slots: [7, 8, 9] }],
    location: "M308",
    syllabus: "AI科傳組必修。教授作業系統核心概念：進程及多線程同步、排程演算法、記憶體管理及死結預防。Linux 實作包含 Shell Script CLI 運作管理、使用者安防及 AWS/GCP 雲端伺服器建置操作實務。",
    isRequired: true,
    category: "核心必修"
  },

  // ==========================================
  // 5. JOUR (新聞學系 - 010)
  // ==========================================
  {
    id: "jour_106_01_a1",
    code: "JOUR-106-01-A1",
    name: "新聞學 Journalism",
    departmentId: "010",
    credits: 2,
    instructor: "陳雅琳",
    timeSlots: [{ day: 1, slots: [2, 3] }],
    location: "CB201",
    syllabus: "輔系選課表科目。認識新聞媒體的本質、演進與大眾傳播理論。探討真實報導、查證守門人精神、第四權功能，以及數位時代下假新聞與流量至上思維對現代社會秩序和言論環境產生的巨大衝擊。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_130_01_a1",
    code: "JOUR-130-01-A1",
    name: "新聞攝影與構圖 Press Photography and Composition",
    departmentId: "010",
    credits: 2,
    instructor: "張乾琦",
    timeSlots: [{ day: 1, slots: [6, 7] }],
    location: "CB302",
    syllabus: "輔系選課表科目。教授新聞紀實攝影心法、相機基礎操作（光圈、快門、感光度ISO）及黃金比例、對稱式等多元構圖美學。藉由街頭實地外拍拍片，深化用單一精彩畫面敘說深刻故事的能力。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_146_01_a1",
    code: "JOUR-146-01-A1",
    name: "新聞編審與編輯 News Copyediting and Layout Design",
    departmentId: "010",
    credits: 2,
    instructor: "劉資敏",
    timeSlots: [{ day: 2, slots: [6, 7] }],
    location: "CB303",
    syllabus: "輔系選課表科目。學習報紙與數位新聞的標題提煉、內文編審改寫、圖片配搭與版面規劃。教授InDesign排版工具與現代網頁多欄位視覺呈現法，提升讀者留存率與可讀性。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_132_01_a1",
    code: "JOUR-132-01-A1",
    name: "新聞採訪寫作 News Reporting and Writing",
    departmentId: "010",
    credits: 2,
    instructor: "李志德",
    timeSlots: [{ day: 3, slots: [2, 3] }],
    location: "CB202",
    syllabus: "輔系選課表科目。訓練學生敏銳觀察力、約訪要領、口頭詰問探掘與傾聽提問。實作演練倒金字塔式、非虛構紀實與人物專訪，產出極富閱讀深度與客觀信度之報導。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_131_01_a1",
    code: "JOUR-131-01-A1",
    name: "影音新聞拍攝與剪輯 Video News Recording and Editing",
    departmentId: "010",
    credits: 2,
    instructor: "莊榮宏",
    timeSlots: [{ day: 3, slots: [6, 7] }],
    location: "CB101",
    syllabus: "輔系選課表科目。數位影音報導基礎。教授單兵手持拍機或使用單眼相機進行影像收支操作、收音技巧、多角度運鏡。上機實習Premiere剪輯，學會快節奏影音配音旁白與字幕合軌。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_278_01_a1",
    code: "JOUR-278-01-A1",
    name: "資料新聞與視覺化 Data Journalism",
    departmentId: "010",
    credits: 2,
    instructor: "張小蘋",
    timeSlots: [{ day: 4, slots: [6, 7] }],
    location: "W401",
    syllabus: "輔系選課表科目。講述如何透過公共API、政府開放資料(Open Data)進行資料爬取與整理，並使用資料視覺化模組將枯燥數據編排為具有批判深度之資料新聞。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_280_01_a1",
    code: "JOUR-280-01-A1",
    name: "新聞數據解讀與應用 News Data Analytics & Interpretation",
    departmentId: "010",
    credits: 2,
    instructor: "林照真",
    timeSlots: [{ day: 4, slots: [2, 3] }],
    location: "CB401",
    syllabus: "輔系選課表科目。培植數據素養。教導如何透過Excel、SPSS對社會普查、選舉走勢與企業財報數據進行多維交叉分析，提煉出數據背後隱含之關鍵社會真相與新聞線索。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_288_01_a1",
    code: "JOUR-288-01-A1",
    name: "新聞英文(一) News English I",
    departmentId: "010",
    credits: 2,
    instructor: "江雅綺",
    timeSlots: [{ day: 1, slots: [8, 9] }],
    location: "CB403",
    syllabus: "輔系選課表科目（全學年）。研析國際頂尖媒體如紐約時報、經濟學人、BBC之頭條報導。精煉國際政治、金融與科技脈動相關專業英語詞彙，深化專業外語閱讀與口述提煉能力。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_289_01_a1",
    code: "JOUR-289-01-A1",
    name: "新聞英文(二) News English II",
    departmentId: "010",
    credits: 2,
    instructor: "江雅綺",
    timeSlots: [{ day: 2, slots: [2, 3] }],
    location: "CB403",
    syllabus: "輔系選課表科目（全學年）。新聞英文(一)進階篇。著重自主產出英文新聞摘要與撰寫。上課安排情境模擬外媒採訪與英文即時播報演練，全面拉升國際化新聞實戰口說競爭力。",
    isRequired: false,
    category: "專業選修",
    prerequisites: ["JOUR-288-01-A1"]
  },
  {
    id: "jour_283_01_a1",
    code: "JOUR-283-01-A1",
    name: "網路新聞 Online News",
    departmentId: "010",
    credits: 2,
    instructor: "何建明",
    timeSlots: [{ day: 5, slots: [2, 3] }],
    location: "CB202",
    syllabus: "輔系選課表科目。探討網路社群分眾、SEO搜尋引擎最佳化、資訊超連結結構、長文敘事及網頁自適應設計(Responsive Web Design)在當代新聞媒體發布管道之融合實務，並了解數位平台受眾心理。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_284_01_a1",
    code: "JOUR-284-01-A1",
    name: "影音新聞製作 Advanced Video News Production",
    departmentId: "010",
    credits: 2,
    instructor: "莊榮宏",
    timeSlots: [{ day: 4, slots: [8, 9] }],
    location: "CB101",
    syllabus: "輔系選課表科目。專注於高難度的專題報導、人物特寫與即時棚內連線錄播實務。小組需完成具有新聞品質的完整紀錄專題或深度多鏡頭新聞專題影片，奠定專業電視與網路台導播編導實力。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_245_01_a1",
    code: "JOUR-245-01-A1",
    name: "傳播研究方法 Communication Research Methods",
    departmentId: "010",
    credits: 2,
    instructor: "潘家慶",
    timeSlots: [{ day: 5, slots: [4, 5] }],
    location: "CB301",
    syllabus: "輔系選課表科目。研究大型傳播媒介效應與閱聽人心理之研究工具。學會設計量化問卷、質化焦點團體訪談、文本內容分析法與學術論文寫作邏輯，是攻讀國內外傳播研究所必學基石。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jour_338_01_a1",
    code: "JOUR-338-01-A1",
    name: "新聞倫理 Journalism Ethics",
    departmentId: "010",
    credits: 2,
    instructor: "胡元輝",
    timeSlots: [{ day: 5, slots: [6, 7] }],
    location: "CB203",
    syllabus: "輔系選課表科目。深度辯證新聞第四權自由與個人隠私權衝突、煽色腥假新聞、商業置入性行銷、演算法推播偏見、公關誘餌與假消息作戰等道德邊界與專業規範要求，建立新聞人的良心防線。",
    isRequired: false,
    category: "專業選修"
  },

  // ==========================================
  // 6. JALL (日本語文學系 - 340)
  // ==========================================
  {
    id: "jall_101_01_a1",
    code: "JALL-101-01-A1",
    name: "初級日語(一) Elementary Japanese I",
    departmentId: "340",
    credits: 3,
    instructor: "中川正樹",
    timeSlots: [{ day: 1, slots: [2, 3, 4] }],
    location: "G401",
    syllabus: "輔系核心必修（18學分中之一）。奠定基礎日語的發音（五十音、濁音、半濁音、拗音、促音、長音）及基本生活問候。教授基本句型與動詞變化（包括動詞ます形及各基本時態）。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "jall_102_01_a1",
    code: "JALL-102-01-A1",
    name: "初級日語(二) Elementary Japanese II",
    departmentId: "340",
    credits: 3,
    instructor: "中川正樹",
    timeSlots: [{ day: 1, slots: [6, 7, 8] }],
    location: "G401",
    syllabus: "輔系核心必修（18學分中之一）。初級日語(一)延續，講授日語基本助詞的活用、形容詞變化與各類生活實用句型，並導入動詞「て形」、「た形」、「ない形」等進階動詞變化，以JLPT N5為目標。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["JALL-101-01-A1"]
  },
  {
    id: "jall_103_01_a1",
    code: "JALL-103-01-A1",
    name: "初級日語會話(一) Basic Japanese Conversation I",
    departmentId: "340",
    credits: 3,
    instructor: "松本薰",
    timeSlots: [{ day: 3, slots: [2, 3, 4] }],
    location: "G403",
    syllabus: "輔系核心必修（18學分中之一）。藉由小組角色扮演、生活場景模擬實作與高密度的口說練習，訓練日語五十音、簡單日常對話之聽說即戰力與表達自信心。",
    isRequired: true,
    category: "核心必修"
  },
  {
    id: "jall_104_01_a1",
    code: "JALL-104-01-A1",
    name: "初級日語會話(二) Basic Japanese Conversation II",
    departmentId: "340",
    credits: 3,
    instructor: "松本薰",
    timeSlots: [{ day: 3, slots: [6, 7, 8] }],
    location: "G403",
    syllabus: "輔系核心必修（18學分中之一）。初級日語會話(一)之進階，強化旅行購物、問路、預約、點餐等情境口說對話演練，引導學生自然融入日本道地對談文化。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["JALL-103-01-A1"]
  },
  {
    id: "jall_201_01_a1",
    code: "JALL-201-01-A1",
    name: "中級日語(一) Intermediate Japanese I",
    departmentId: "340",
    credits: 3,
    instructor: "蔡嘉琪",
    timeSlots: [{ day: 2, slots: [2, 3, 4] }],
    location: "G402",
    syllabus: "輔系核心必修（18學分中之一）。以系統性文法為骨幹，探討日語動詞變化（被動、使役、使役被動、意向、可能等），進一步分析基礎複合動詞，銜接 JLPT N4 核心實力。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["JALL-102-01-A1"]
  },
  {
    id: "jall_202_01_a1",
    code: "JALL-202-01-A1",
    name: "中級日語(二) Intermediate Japanese II",
    departmentId: "340",
    credits: 3,
    instructor: "蔡嘉琪",
    timeSlots: [{ day: 2, slots: [6, 7, 8] }],
    location: "G402",
    syllabus: "輔系核心必修（18學分中之一）。中級日語(一)之延續課程。奠定敬語（尊敬語、自謙語）與日常生活正式表達方式，探討複雜的關係子句與短文閱讀。",
    isRequired: true,
    category: "核心必修",
    prerequisites: ["JALL-201-01-A1"]
  },
  {
    id: "jall_136_01_a1",
    code: "JALL-136-01-A1",
    name: "外文日文(一) Basic Japanese I",
    departmentId: "340",
    credits: 2,
    instructor: "蔡嘉琪",
    timeSlots: [{ day: 4, slots: [6, 7] }],
    location: "G302",
    syllabus: "日語初學者首選。介紹五十音、基礎實用生活會話與日本傳統禮儀，擴充國際視野。選修學科。",
    isRequired: false,
    category: "基礎工具"
  },
  {
    id: "jall_230_01_a1",
    code: "JALL-230-01-A1",
    name: "日語配音 Japanese Dubbing",
    departmentId: "340",
    credits: 2,
    instructor: "百瀨英樹",
    timeSlots: [{ day: 5, slots: [6, 7] }],
    location: "J312",
    syllabus: "日文專業培訓。研究腔調起伏與日本配音情感宣洩點，矯正日語發音，銜接自媒體影視與日本商業對接人才。選修學科。",
    isRequired: false,
    category: "進階應用"
  },
  {
    id: "jall_301_01_a1",
    code: "JALL-301-01-A1",
    name: "商務日本語 Business Japanese",
    departmentId: "340",
    credits: 3,
    instructor: "蔡嘉琪",
    timeSlots: [{ day: 4, slots: [2, 3, 4] }],
    location: "G402",
    syllabus: "選修課程。專為進入日商、知名企業跨國貿易工作所設計。講授商務書信、日商會議禮儀、商場談判斡旋語氣，以及商業視訊和電話對答禮節。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jall_302_01_a1",
    code: "JALL-302-01-A1",
    name: "日本社會與文化 Japanese Society & Culture",
    departmentId: "340",
    credits: 3,
    instructor: "百瀨英樹",
    timeSlots: [{ day: 5, slots: [2, 3, 4] }],
    location: "G401",
    syllabus: "選修課程。深入解析昭和與平成至令和世代的文化變遷，探討動漫次文化、茶道花道文化、神道信仰，以及當代日本高齡化、少子化衝擊之社會現象。",
    isRequired: false,
    category: "專業選修"
  },
  {
    id: "jall_215_01_a1",
    code: "JALL-215-01-A1",
    name: "日本觀光與文化實務 Japanese Tourism & Culture Practicum",
    departmentId: "340",
    credits: 2,
    instructor: "松本薰",
    timeSlots: [{ day: 5, slots: [7, 8] }],
    location: "G403",
    syllabus: "選修課程。從觀光導遊與旅遊作家視角，探討日式溫泉旅館款待精神（Omotenashi）、古蹟參訪、日本鐵道旅行與地方創生，鍛煉實務應對與行銷力。",
    isRequired: false,
    category: "專業選修"
  }
];

// Seed Comments for active catalogs
export const INITIAL_COMMENTS: CourseComment[] = [
  {
    id: "comment_1",
    courseId: "info_107_01_a1",
    reviewer: "資傳系三 林同學",
    ratingDifficulty: 4,
    ratingValue: 5,
    content: "連老師的大推！雖然剛開始學 HTML/CSS 與 PhotoShop 時要花心思，但能打下極實用的前端美學底子！",
    date: "2026-03-12"
  },
  {
    id: "comment_2",
    courseId: "prad_109_01_a1",
    reviewer: "公廣系二 陳同學",
    ratingDifficulty: 3,
    ratingValue: 5,
    content: "洪老師上課熱情爆表，學期專案把創意和行銷一氣呵成實作出來，學到非常紮實的文案與簡報硬實力！",
    date: "2026-04-01"
  }
];

// Initial default user profiles (Lin Hsiao Hua, Year 2, Section A)
export const INITIAL_USER: UserProfile = {
  name: "林小華",
  studentId: "A113070059",
  email: "A113070059@mail.shu.edu.tw",
  isLoggedIn: false,
  majorDeptId: "070", // Target 資訊傳播學系
  minorDeptId: "050", // Minor: 公共關係暨廣告學系
  classGrade: "二年級",
  classGroup: "甲",
  completedCourseIds: ["info_107_01_a1"],
  simulatedCourseIds: ["prad_109_01_a1", "prad_102_01_a1"]
};
